[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "cc23c786049328c93138da14e7020a464d707a23"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "0.1.0"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Revise]]
deps = ["Distributed", "FileWatching", "LibGit2", "OrderedCollections", "Pkg", "REPL", "Random", "Test", "Unicode"]
git-tree-sha1 = "d49990fc136cb88d5b48fb803bf5f44244e26b8d"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "0.5.4"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
